# Generated by Django 6.0.4 on 2026-06-09 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhl_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField(default=0)),
                ('position', models.CharField(choices=[('C', 'Center'), ('LW', 'Left Wing'), ('RW', 'Right Wing'), ('D', 'Defenseman')], max_length=3)),
                ('team', models.CharField(max_length=100)),
                ('headshot_url', models.CharField(blank=True, max_length=500)),
                ('ranking', models.IntegerField()),
                ('previous_ranking', models.IntegerField(blank=True, null=True)),
                ('iq_score', models.FloatField(default=0.0)),
                ('consecutive_weeks', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('primary_assists', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('plus_minus', models.IntegerField(default=0)),
                ('time_on_ice_per_game', models.FloatField(default=0.0)),
                ('shots_on_goal', models.IntegerField(default=0)),
                ('shooting_percentage', models.FloatField(default=0.0)),
                ('power_play_goals', models.IntegerField(default=0)),
                ('power_play_points', models.IntegerField(default=0)),
                ('short_handed_goals', models.IntegerField(default=0)),
                ('game_winning_goals', models.IntegerField(default=0)),
                ('points_per_60', models.FloatField(default=0.0)),
                ('primary_assists_per_60', models.FloatField(default=0.0)),
                ('plus_minus_per_60', models.FloatField(default=0.0)),
                ('corsi_percentage', models.FloatField(default=0.0)),
                ('xgoals_percentage', models.FloatField(default=0.0)),
                ('zone_entry_success', models.FloatField(default=0.0)),
                ('defensive_zone_exits', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ranking'],
            },
        ),
        migrations.CreateModel(
            name='PlayerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='playerstats.player')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('season', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('week_number', 'season')},
            },
        ),
        migrations.CreateModel(
            name='PlayerDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('current_rank', models.IntegerField()),
                ('previous_rank', models.IntegerField(blank=True, null=True)),
                ('iq_score_at_time', models.FloatField()),
                ('consecutive_weeks_at_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='playerstats.player')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descriptions', to='playerstats.week')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='last_seen_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_players', to='playerstats.week'),
        ),
        migrations.CreateModel(
            name='PlayerWeeklyAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('iq_score', models.FloatField()),
                ('points', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_appearances', to='playerstats.player')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_appearances', to='playerstats.week')),
            ],
            options={
                'ordering': ['-week__start_date'],
                'unique_together': {('player', 'week')},
            },
        ),
    ]
