# Generated by Django 6.0.4 on 2026-06-10 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhl_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField(default=0)),
                ('position', models.CharField(choices=[('C', 'Center'), ('LW', 'Left Wing'), ('RW', 'Right Wing'), ('D', 'Defenseman')], max_length=3)),
                ('team', models.CharField(max_length=100)),
                ('headshot_url', models.CharField(blank=True, max_length=500)),
                ('ranking', models.IntegerField()),
                ('iq_score', models.FloatField(default=0.0)),
                ('games', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('primary_assists', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('plus_minus', models.IntegerField(default=0)),
                ('time_on_ice_per_game', models.FloatField(default=0.0)),
                ('points_per_60', models.FloatField(default=0.0)),
                ('primary_assists_per_60', models.FloatField(default=0.0)),
                ('plus_minus_per_60', models.FloatField(default=0.0)),
                ('corsi_percentage', models.FloatField(default=0.0)),
                ('xgoals_percentage', models.FloatField(default=0.0)),
                ('zone_entry_success', models.FloatField(default=0.0)),
                ('defensive_zone_exits', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ranking'],
            },
        ),
        migrations.CreateModel(
            name='PlayerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='playerstats.player')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerWeeklySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('consecutive_weeks', models.IntegerField(default=1)),
                ('current_ranking', models.IntegerField()),
                ('previous_ranking', models.IntegerField(blank=True, null=True)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('plus_minus', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_snapshots', to='playerstats.player')),
            ],
            options={
                'ordering': ['-week'],
                'unique_together': {('player', 'week')},
            },
        ),
    ]
