# Generated by Django 6.0.4 on 2026-06-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerstats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='penalty_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='xgoals_against_per_60',
            field=models.FloatField(default=0.0),
        ),
    ]
