# Generated by Django 6.0.4 on 2026-06-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerstats', '0002_player_penalty_minutes_player_xgoals_against_per_60'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='defensive_zone_exits',
        ),
        migrations.RemoveField(
            model_name='player',
            name='zone_entry_success',
        ),
    ]
