# Generated by Django 6.0.4 on 2026-04-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('overtime_losses', models.IntegerField()),
                ('points', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
